#!/usr/bin/env python3
"""Build a sealed natural-language Euclidean-algorithm reasoning benchmark."""

from __future__ import annotations

import argparse
import hashlib
import json
import math
import random
from pathlib import Path


TRAIN_TEMPLATES = (
    "Determine whether {a}x + {b}y = {c} is solvable over the integers.",
    "Can {c} be an integer linear combination of {a} and {b}?",
    "Do signed whole-number coefficients on {b} and {a} produce the target {c}?",
    "Starting from zero with reversible moves of {a} and {b}, is {c} reachable?",
    "Test whether {c} belongs to the integer span generated by {a} and {b}.",
    "May integer multiples of {b} and {a} sum to {c}?",
    "Ignore {d}; decide if some integers r and s satisfy {a}r + {b}s = {c}.",
    "Is {c} contained in the additive subgroup generated by {a} and {b}?",
)

DEV_TEMPLATES = (
    "A marker can move forward or backward by {a} or {b}. Can it reach {c} from zero?",
    "Decide if the equation {c} = {b}n + {a}m has an integer solution.",
    "Can signed batches of sizes {a} and {b} create a net amount of {c}?",
)

TEST_TEMPLATES = (
    "A game token has reversible jumps of {a} and {b} spaces. Is square {c} accessible from square zero?",
    "Could a balance change by exactly {c} using arbitrary signed groups of {a} and {b}?",
    "Seek integers multiplying {a} and {b} whose sum is the specified value {c}.",
    "Does the smallest integer additive group containing {b} and {a} also contain {c}?",
)


def load_jsonl(path: Path) -> list[dict]:
    return [json.loads(line) for line in path.read_text(encoding="utf-8").splitlines() if line.strip()]


def write(path: Path, rows: list[dict]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("".join(json.dumps(row, sort_keys=True) + "\n" for row in rows), encoding="utf-8")


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def euclidean_steps(a: int, b: int) -> list[tuple[int, int, int, int]]:
    dividend, divisor = max(a, b), min(a, b)
    steps = []
    while divisor:
        quotient, remainder = divmod(dividend, divisor)
        steps.append((dividend, quotient, divisor, remainder))
        dividend, divisor = divisor, remainder
    return steps


def completion(a: int, b: int, c: int, gcd_value: int, solvable: bool) -> str:
    steps = " ".join(
        f"Euclidean step: {dividend} = {quotient} times {divisor} plus {remainder}."
        for dividend, quotient, divisor, remainder in euclidean_steps(a, b)
    )
    relation = "does" if solvable else "does not"
    return f"{steps} Therefore the greatest common divisor is {gcd_value}, and it {relation} divide {c}."


def instances(
    seed: int,
    split: str,
    count: int,
    templates: tuple[str, ...],
    used: set[tuple[int, int, int]],
    id_prefix: str,
    gcd_max: int,
    factor_max: int,
    multiplier_max: int,
    coefficient_min: int | None,
    coefficient_max: int | None,
    steps_min: int | None,
    steps_max: int | None,
) -> list[dict]:
    rng = random.Random(seed)
    rows = []
    while len(rows) < count:
        gcd_value = rng.randint(2, gcd_max)
        p, q = rng.randint(2, factor_max), rng.randint(2, factor_max)
        if math.gcd(p, q) != 1:
            continue
        a, b = gcd_value * p, gcd_value * q
        largest_coefficient = max(a, b)
        if coefficient_min is not None and largest_coefficient < coefficient_min:
            continue
        if coefficient_max is not None and largest_coefficient > coefficient_max:
            continue
        step_count = len(euclidean_steps(a, b))
        if steps_min is not None and step_count < steps_min:
            continue
        if steps_max is not None and step_count > steps_max:
            continue
        solvable = len(rows) % 2 == 0
        multiplier = rng.choice([value for value in range(-multiplier_max, multiplier_max + 1) if value])
        c = gcd_value * multiplier if solvable else gcd_value * multiplier + rng.randint(1, gcd_value - 1)
        key = (a, b, c)
        if key in used:
            continue
        used.add(key)
        statement = templates[len(rows) % len(templates)].format(a=a, b=b, c=c, d=abs(c) + 43)
        prompt = (
            f"Respond only in English.\nProblem: {statement}\n"
            "Relevant concept: the Euclidean algorithm and the greatest-common-divisor criterion for linear Diophantine equations.\n"
            "Task: Give the complete Euclidean algorithm. Write every division as 'Euclidean step: A = Q times B plus R.' "
            "Then state exactly whether the gcd divides the target. Do not give witnesses or cite a theorem.\nArgument: "
        )
        expected = completion(a, b, c, gcd_value, solvable)
        rows.append(
            {
                "id": f"{id_prefix}-{split}-{len(rows):04d}",
                "family": "diophantine_euclidean_trace",
                "split": split,
                "surface": split,
                "prompt": prompt,
                "completion": expected,
                "expected": expected,
                "parameters": {"a": a, "b": b, "c": c, "gcd": gcd_value, "solvable": solvable},
            }
        )
    return rows


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output-dir", type=Path, required=True)
    parser.add_argument("--exclude", type=Path, action="append", default=[])
    parser.add_argument("--train", type=int, default=800)
    parser.add_argument("--valid", type=int, default=160)
    parser.add_argument("--test", type=int, default=200)
    parser.add_argument("--seed", type=int, default=20260721)
    parser.add_argument("--id-prefix", default="dav4")
    parser.add_argument("--gcd-max", type=int, default=45)
    parser.add_argument("--factor-max", type=int, default=210)
    parser.add_argument("--multiplier-max", type=int, default=25)
    parser.add_argument("--coefficient-min", type=int)
    parser.add_argument("--coefficient-max", type=int)
    parser.add_argument("--steps-min", type=int)
    parser.add_argument("--steps-max", type=int)
    args = parser.parse_args()

    used: set[tuple[int, int, int]] = set()
    for path in args.exclude:
        for row in load_jsonl(path):
            params = row.get("parameters")
            if not isinstance(params, dict) or not {"a", "b", "c"} <= params.keys():
                continue
            used.add((params["a"], params["b"], params["c"]))
    excluded_count = len(used)
    views = {
        "train": instances(args.seed, "train", args.train, TRAIN_TEMPLATES, used, args.id_prefix, args.gcd_max, args.factor_max, args.multiplier_max, args.coefficient_min, args.coefficient_max, args.steps_min, args.steps_max),
        "valid": instances(args.seed + 1, "valid", args.valid, DEV_TEMPLATES, used, args.id_prefix, args.gcd_max, args.factor_max, args.multiplier_max, args.coefficient_min, args.coefficient_max, args.steps_min, args.steps_max),
        "test": instances(args.seed + 2, "test", args.test, TEST_TEMPLATES, used, args.id_prefix, args.gcd_max, args.factor_max, args.multiplier_max, args.coefficient_min, args.coefficient_max, args.steps_min, args.steps_max),
    }
    for split, rows in views.items():
        write(args.output_dir / f"{split}.prompts.jsonl", [{"id": row["id"], "family": row["family"], "surface": row["surface"], "prompt": row["prompt"]} for row in rows])
        write(args.output_dir / f"{split}.verifier.jsonl", rows)
        if split != "test":
            write(args.output_dir / "training" / f"{split}.jsonl", [{"prompt": row["prompt"], "completion": row["completion"], "metadata": {"id": row["id"], "family": row["family"]}} for row in rows])
    manifest = {
        "seed": args.seed,
        "numeric_range": {"gcd_max": args.gcd_max, "factor_max": args.factor_max, "multiplier_max": args.multiplier_max, "coefficient_min": args.coefficient_min, "coefficient_max": args.coefficient_max, "steps_min": args.steps_min, "steps_max": args.steps_max},
        "counts": {split: len(rows) for split, rows in views.items()},
        "template_counts": {"train": len(TRAIN_TEMPLATES), "valid": len(DEV_TEMPLATES), "test": len(TEST_TEMPLATES)},
        "excluded_parameters": excluded_count,
        "parameter_overlap": 0,
        "test_prompt_sha256": sha256(args.output_dir / "test.prompts.jsonl"),
        "test_verifier_sha256": sha256(args.output_dir / "test.verifier.jsonl"),
    }
    (args.output_dir / "manifest.json").write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(json.dumps(manifest, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
