#!/usr/bin/env python3
"""Build a disjoint Diophantine benchmark with train/dev/test language separation."""

from __future__ import annotations

import argparse
import hashlib
import json
import math
import random
from pathlib import Path


TRAIN_TEMPLATES = (
    "Do integers x and y satisfy {a}x + {b}y = {c}? Apply the common-divisor criterion.",
    "Can {c} be expressed as {a} times one integer plus {b} times another? Give the decisive gcd check.",
    "Determine whether {c} is an integer linear combination of {a} and {b}.",
    "Are there signed whole-number coefficients for {a} and {b} whose weighted sum is {c}?",
    "Starting at zero, moves of {a} or {b} units may be taken forward or backward. Is {c} reachable?",
    "A ledger permits adjustments by any integer multiple of {a} and any integer multiple of {b}. Can the net adjustment be {c}?",
    "Does the additive set generated by {a} and {b}, allowing negative coefficients, contain {c}?",
    "Find whether some integers p and q make {b}q + {a}p equal the target {c}.",
    "Ignore the reference value {d}. Test if {a}u + {b}v can equal {c} for integer u and v.",
    "The available signed increments have sizes {a} and {b}. Decide if their integer combination can total {c}.",
    "Is the equation with right-hand side {c} and left-hand side {b}s + {a}r solvable over the integers?",
    "Test membership of {c} in the integer span of the two numbers {b} and {a}.",
)

DEV_TEMPLATES = (
    "A counter begins at zero and each operation changes it by either {a} or {b}, in either direction. Can it finish at {c}?",
    "May {c} be assembled from any signed number of blocks worth {a} and {b}? Use a greatest-common-divisor test.",
    "Decide if the Diophantine relation {c} = {a}m + {b}n admits integer m and n.",
    "Among all sums formed from integer multiples of {a} and {b}, does one equal {c}?",
)

TEST_TEMPLATES = (
    "A robot on an integer track has reversible jumps of lengths {a} and {b}. Is position {c} accessible from the origin?",
    "A balance can be altered by signed batches of {a} grams and {b} grams. Can its total alteration be exactly {c} grams?",
    "Seek whole numbers, which may be positive, zero, or negative, so that multiplying them by {a} and {b} gives a sum of {c}.",
    "Does {c} occur in the smallest additive subgroup of the integers containing both {a} and {b}?",
)


def load_jsonl(path: Path) -> list[dict]:
    return [json.loads(line) for line in path.read_text(encoding="utf-8").splitlines() if line.strip()]


def write(path: Path, rows: list[dict]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("".join(json.dumps(row, sort_keys=True) + "\n" for row in rows), encoding="utf-8")


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def instances(
    seed: int,
    split: str,
    count: int,
    templates: tuple[str, ...],
    used: set[tuple[int, int, int]],
) -> list[dict]:
    rng = random.Random(seed)
    rows = []
    while len(rows) < count:
        gcd_value = rng.randint(2, 45)
        p, q = rng.randint(2, 190), rng.randint(2, 190)
        if math.gcd(p, q) != 1:
            continue
        a, b = gcd_value * p, gcd_value * q
        solvable = len(rows) % 2 == 0
        multiplier = rng.choice([value for value in range(-24, 25) if value])
        c = gcd_value * multiplier if solvable else gcd_value * multiplier + rng.randint(1, gcd_value - 1)
        key = (a, b, c)
        if key in used:
            continue
        used.add(key)
        template = templates[len(rows) % len(templates)]
        statement = template.format(a=a, b=b, c=c, d=abs(c) + 31)
        concept = "the greatest-common-divisor criterion for linear Diophantine equations"
        prompt = (
            f"Respond only in English.\nProblem: {statement}\nRelevant concept: {concept}.\n"
            "Task: State exactly one sentence giving the greatest common divisor and whether it divides the right-hand side. "
            "Do not state a conclusion, witness, or any other claim.\nClaim: "
        )
        relation = "does" if solvable else "does not"
        completion = f"The greatest common divisor is {gcd_value}, and it {relation} divide {c}."
        identifier = f"dav3-{split}-{len(rows):04d}"
        rows.append(
            {
                "id": identifier,
                "family": "diophantine_solvability",
                "split": split,
                "surface": split,
                "template_id": len(rows) % len(templates),
                "prompt": prompt,
                "completion": completion,
                "expected": completion,
                "parameters": {"a": a, "b": b, "c": c, "gcd": gcd_value, "solvable": solvable},
            }
        )
    return rows


def variants(row: dict) -> list[dict]:
    params = row["parameters"]
    prefix = row["prompt"].split("Task:", 1)[0]
    gcd_value, c = params["gcd"], params["c"]
    relation = "does" if params["solvable"] else "does not"
    metadata = {"id": row["id"], "family": row["family"], "template_id": row["template_id"]}
    return [
        {"prompt": row["prompt"], "completion": row["completion"], "metadata": {**metadata, "stage": "joint"}},
        {"prompt": prefix + "Task: State exactly one sentence giving the greatest common divisor. Do not add any other claim.\nClaim: ", "completion": f"The greatest common divisor is {gcd_value}.", "metadata": {**metadata, "stage": "gcd"}},
        {"prompt": prefix + f"Verified intermediate claim: The greatest common divisor is {gcd_value}.\nTask: State exactly one sentence saying whether {gcd_value} divides {c}. Do not add any other claim.\nClaim: ", "completion": f"It {relation} divide {c}.", "metadata": {**metadata, "stage": "divisibility"}},
    ]


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output-dir", type=Path, required=True)
    parser.add_argument("--exclude", type=Path, action="append", default=[])
    parser.add_argument("--train", type=int, default=800)
    parser.add_argument("--valid", type=int, default=160)
    parser.add_argument("--test", type=int, default=200)
    parser.add_argument("--seed", type=int, default=20260720)
    args = parser.parse_args()

    used: set[tuple[int, int, int]] = set()
    for path in args.exclude:
        for row in load_jsonl(path):
            params = row["parameters"]
            used.add((params["a"], params["b"], params["c"]))
    excluded_count = len(used)
    views = {
        "train": instances(args.seed, "train", args.train, TRAIN_TEMPLATES, used),
        "valid": instances(args.seed + 1, "valid", args.valid, DEV_TEMPLATES, used),
        "test": instances(args.seed + 2, "test", args.test, TEST_TEMPLATES, used),
    }
    for split, rows in views.items():
        write(args.output_dir / f"{split}.prompts.jsonl", [{"id": row["id"], "family": row["family"], "surface": row["surface"], "prompt": row["prompt"]} for row in rows])
        write(args.output_dir / f"{split}.verifier.jsonl", rows)
        if split != "test":
            write(args.output_dir / "training" / f"{split}.jsonl", [variant for row in rows for variant in variants(row)])
    manifest = {
        "seed": args.seed,
        "counts": {split: len(rows) for split, rows in views.items()},
        "template_counts": {"train": len(TRAIN_TEMPLATES), "valid": len(DEV_TEMPLATES), "test": len(TEST_TEMPLATES)},
        "training_expanded": {split: len(rows) * 3 for split, rows in views.items() if split != "test"},
        "excluded_parameters": excluded_count,
        "parameter_overlap": 0,
        "test_prompt_sha256": sha256(args.output_dir / "test.prompts.jsonl"),
        "test_verifier_sha256": sha256(args.output_dir / "test.verifier.jsonl"),
    }
    (args.output_dir / "manifest.json").write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(json.dumps(manifest, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
