#!/usr/bin/env python3
"""Build a larger sealed natural-language Diophantine atomic curriculum."""

from __future__ import annotations

import argparse
import hashlib
import json
import math
import random
from pathlib import Path


TRAIN_TEMPLATES = (
    "Does the equation {a}x + {b}y = {c} have an integer solution? Use the greatest common divisor criterion.",
    "Can integers r and s make {b} times s plus {a} times r equal {c}? Give the decisive numerical check.",
    "Decide whether {c} is an integer linear combination of {a} and {b}; base the decision on their greatest common divisor.",
    "Ignore the unrelated number {d}. Determine whether some integers u and v satisfy {a}u + {b}v = {c}.",
)

NOVEL_TEMPLATES = (
    "Judge whether {c} belongs to the integer span generated by {a} and {b}. State the gcd obstruction or permission.",
    "A balance changes by multiples of {a} and {b}. Can its net change be exactly {c}? Use the common-divisor test.",
)


def write(path: Path, rows: list[dict]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("".join(json.dumps(row, sort_keys=True) + "\n" for row in rows), encoding="utf-8")


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def instances(seed: int, split: str, count: int, used: set[tuple[int, int, int]]) -> list[dict]:
    rng = random.Random(seed)
    rows = []
    while len(rows) < count:
        g = rng.randint(2, 35)
        p, q = rng.randint(2, 170), rng.randint(2, 170)
        if math.gcd(p, q) != 1:
            continue
        a, b = g * p, g * q
        solvable = len(rows) % 2 == 0
        k = rng.choice([value for value in range(-20, 21) if value])
        c = g * k if solvable else g * k + rng.randint(1, g - 1)
        key = (a, b, c)
        if key in used:
            continue
        used.add(key)
        if split == "test" and len(rows) >= count // 2:
            template_id = len(rows) % len(NOVEL_TEMPLATES)
            template = NOVEL_TEMPLATES[template_id]
            surface = "novel"
        else:
            template_id = len(rows) % len(TRAIN_TEMPLATES)
            template = TRAIN_TEMPLATES[template_id]
            surface = "familiar"
        statement = template.format(a=a, b=b, c=c, d=abs(c) + 17)
        concept = "the greatest-common-divisor criterion for linear Diophantine equations"
        prompt = (
            f"Respond only in English.\nProblem: {statement}\nRelevant concept: {concept}.\n"
            "Task: State exactly one sentence giving the greatest common divisor and whether it divides the right-hand side. "
            "Do not state a conclusion, witness, or any other claim.\nClaim: "
        )
        relation = "does" if solvable else "does not"
        completion = f"The greatest common divisor is {g}, and it {relation} divide {c}."
        identifier = f"dav2-{split}-{len(rows):04d}"
        rows.append({"id": identifier, "family": "diophantine_solvability", "split": split, "surface": surface, "prompt": prompt, "completion": completion, "expected": completion, "parameters": {"a": a, "b": b, "c": c, "gcd": g, "solvable": solvable}})
    return rows


def variants(row: dict) -> list[dict]:
    params = row["parameters"]
    prefix = row["prompt"].split("Task:", 1)[0]
    g, c = params["gcd"], params["c"]
    relation = "does" if params["solvable"] else "does not"
    metadata = {"id": row["id"], "family": row["family"]}
    return [
        {"prompt": row["prompt"], "completion": row["completion"], "metadata": {**metadata, "stage": "joint"}},
        {"prompt": prefix + "Task: State exactly one sentence giving the greatest common divisor. Do not add any other claim.\nClaim: ", "completion": f"The greatest common divisor is {g}.", "metadata": {**metadata, "stage": "gcd"}},
        {"prompt": prefix + f"Verified intermediate claim: The greatest common divisor is {g}.\nTask: State exactly one sentence saying whether {g} divides {c}. Do not add any other claim.\nClaim: ", "completion": f"It {relation} divide {c}.", "metadata": {**metadata, "stage": "divisibility"}},
    ]


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output-dir", type=Path, required=True)
    parser.add_argument("--train", type=int, default=600)
    parser.add_argument("--valid", type=int, default=120)
    parser.add_argument("--test", type=int, default=200)
    parser.add_argument("--seed", type=int, default=20260719)
    args = parser.parse_args()
    used: set[tuple[int, int, int]] = set()
    views = {
        "train": instances(args.seed, "train", args.train, used),
        "valid": instances(args.seed + 1, "valid", args.valid, used),
        "test": instances(args.seed + 2, "test", args.test, used),
    }
    for split, rows in views.items():
        write(args.output_dir / f"{split}.prompts.jsonl", [{"id": row["id"], "family": row["family"], "surface": row["surface"], "prompt": row["prompt"]} for row in rows])
        write(args.output_dir / f"{split}.verifier.jsonl", rows)
        if split in {"train", "valid"}:
            write(args.output_dir / "training" / f"{split}.jsonl", [variant for row in rows for variant in variants(row)])
    manifest = {
        "seed": args.seed,
        "counts": {split: len(rows) for split, rows in views.items()},
        "training_expanded": {split: len(rows) * 3 for split, rows in views.items() if split != "test"},
        "parameter_overlap": 0,
        "test_prompt_sha256": sha256(args.output_dir / "test.prompts.jsonl"),
        "test_verifier_sha256": sha256(args.output_dir / "test.verifier.jsonl"),
    }
    (args.output_dir / "manifest.json").write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(json.dumps(manifest, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
